import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Alexandria } from "next/font/google";
import "./globals.css";
import { shadesOfPurple } from "@clerk/themes";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "@mantine/core/styles.css";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
const geistSans = Alexandria({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          fontFamily: geistSans.style.fontFamily,
        },
        signIn: {
          baseTheme: [shadesOfPurple],
          variables: { colorPrimary: "green" },
        },
      }}
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
    >
      <html lang="en" {...mantineHtmlProps}>
        <head>
          <ColorSchemeScript />
        </head>
        <body className={`${geistSans.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <MantineProvider>{children}</MantineProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
